### ISSUE TITLE
Pod tests should also check RELEASE_TESTING [rt.cpan.org #83991]

### ISSUE THREAD

**Issue by xsawyerx** [xsawyerx/module-starter#36]
https://rt.cpan.org/Ticket/Display.html?id=83991

    The Test::Pod and Test::Pod::Coverage using tests don't appear to run only for the releasing 
    author.  This means that later installs can be broken if the installing user has a version of T::P or 
    T::P::C or some other piece of their toolchain that adds new errors.
    
    When that happens, it should NOT block installation of the library!
    
    -- 
    rjbs

**Comment by xsawyerx** [comment]
SREZIC - 2014-02-15 09:18:05

On 2013-03-16 14:35:03, RJBS wrote:
> The Test::Pod and Test::Pod::Coverage using tests don't appear to run
> only for the releasing
> author.  This means that later installs can be broken if the
> installing user has a version of T::P or
> T::P::C or some other piece of their toolchain that adds new errors.
> 
> When that happens, it should NOT block installation of the library!

+1

Regards,
    Slaven

**Comment by chrestomanci** [comment]
I am confused by this bug. It looks like it is fixed in commit b40523fa, but that commit predates the bug report.

Do you think the reporter is confused and is asking for something else? Or was the bug fixed in GitHub but not relased? I notice that before the current 1.62 release in Dec 2013, the prevous release was 4 years earler in Dec 2009. If that is the case, then I think we can close this bug.

**Comment by xsawyerx** [comment]
It might relate to the generated test: https://github.com/xsawyerx/module-starter/blob/master/lib/Module/Starter/Simple.pm#L1094

**Comment by chrestomanci** [comment]
OK, I see what you mean. I have created a pull request to fix that.

**Comment by xsawyerx** [comment]
Dude is on a roll!
