### ISSUE TITLE
Custom Licensing

### ISSUE THREAD

**Issue by matttrach** [xsawyerx/module-starter#69]
I was wondering if there is an easy way to provide a custom license, or potentially if you could provide a license to use when generating a module.

**Comment by Grinnz** [comment]
There are two restrictions at work here.

First, there is a specific set of licenses supported by the CPAN meta-spec: https://metacpan.org/pod/CPAN::Meta::Spec#license

Unfortunately you can't specify a custom license in metadata (and it also won't be recognized by anything) so you'd be left with using one of the 'other licensing' strings mentioned below the list, and depend on your LICENSE pod section or file to specify the details of your license.

Second, Module::Starter's "simple" plugin recognizes only a specific set of license names, which it translates into these meta-spec licenses and license text. These are hardcoded, but in a global hash $Module::Starter::Simple::LICENSES, which you could theoretically add something new to.

Rather than adding more hardcoded licenses, I'd prefer to leverage Software::License as a better overall fix.

**Comment by Grinnz** [comment]
Another option would be to write a Module::Starter::Simple subclass which simply overrides the _license_record sub to return the appropriate structure instead of adding it to $Module::Starter::Simple::LICENSES manually.

**Comment by Grinnz** [comment]
With #70 you would be able to use any Software::License recognized license, or create your own Software::License subclass if needed.

**Comment by Grinnz** [comment]
This has been released as version 1.76.
